name: "Testx"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell -p file sudo xxd --command 'file $(type -p sudo); nm --undefined $(type -p sudo); xxd -c 40 $(type -p sudo)'
